spring:
  application:
    name: CHGuadalquivir
    description: Recover data from C. H. Guadalquivir

  main.allow-bean-definition-overriding: true
  
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  
  datasource:
    batch:
      user: federico
      password: MedinaAzahara2468@
      driverClass: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost/batch?allowPublicKeyRetrieval=true&useSSL=false
      minPoolSize: 1
      maxPoolSize: 3
      maxIdleTime: 500
    
    chguadalquivir:
      user: federico
      password: MedinaAzahara2468@
      driverClass: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost/chguadalquivir?allowPublicKeyRetrieval=true&useSSL=false
      minPoolSize: 1
      maxPoolSize: 3
      maxIdleTime: 500  
    
    
  batch.job.enabled: false
  
  data.mongodb.uri: mongodb://localhost:27017/EmbalsesCHG
  
server:
  port : ${PORT}
#  servlet.context-path: /chguadalquivir
  
batch:
  jdbc:
    testWhileIdle: true
    validationQuery: SELECT 1
    batch.jdbc.pool.size: 6
  
  database:
    incrementer:
      class: org.springframework.jdbc.support.incrementer.MySQLMaxValueIncrementer
      parent: columnIncrementerParent

  lob.handler.class: org.springframework.jdbc.support.lob.DefaultLobHandler
  grid.size: 50
  verify.cursor.position: true
  initialize-schema: always

application:
  importJob:
    cron: 0 45 9 ? * 1,2,3,4,5  
    url: https://www.chguadalquivir.es/saih/EmbalNiv.aspx
    